### ISSUE TITLE
[1.14.4] Forge tag for fruits

### ISSUE THREAD

**Issue by kwpugh** [RayzoRayy/RaysDongles#12]
Hi,

I was wondering if you would consider adding a forge tag for the fruits in your mod?  This would help for cross mod compatibility.

I make a mod called Veggie Way that uses fruits to create fructose powder for making superfood powder.

Here is an example from Simple Farming: https://github.com/enemeez/simplefarming/tree/master/src/main/resources

Thank you for considering.

Regards.

**Comment by RayzoRayy** [comment]
Sure! Ill add the tags Sunday night or Monday sometime when i get home :) Thanks for the suggestion.

**Comment by RayzoRayy** [comment]
Tags added. Update should be available shortly. 2.0.4c

**Comment by kwpugh** [comment]
Thank you.
