### ISSUE TITLE
[1.14.4] Sacktrace in console -IndexOutOfBoundsException - slurpiesdongles.events.GrassDropsEvent.onGrassBroken

### ISSUE THREAD

**Issue by ProsperCraft** [RayzoRayy/RaysDongles#14]
**Describe the bug**
I am trying to find what mod is causing a reload of the sound system cutting off music suddently, and saw this in my log-

In a single player, I got this stacktrace when testing my pack update to Forge 1.0.6

Stacktrace-
https://gist.github.com/ProsperCraft/52a3288f7b7d25d53a8d4f8882781f74
Log
https://gist.github.com/ProsperCraft/fcfb2f9a1a15b24757023edf71fa1c41

**Please complete the following information**
 Forge Version- 28.1.6
Minecraft Version- 1.14.4
Slurpie's Dongles Version(Please indicate exactly which version of my mod you are using)- 
Rays Dongles-1.14.4-2.0.4c

**Please list all mod(s) AND version(s) here that you are currently using along side of my mod**
Modpack -
https://www.curseforge.com/minecraft/modpacks/the-adventures-of-halk

**Comment by RayzoRayy** [comment]
Yeah this particular class is causing alot ot issues. Not to worry, it doesnt do anything anymore so it wont be a hard fix. I just havemt had time yet to go in and remove it, i will try and get an update out later tonight.

**Comment by RayzoRayy** [comment]
Issue should be fixed in latest release. 2.0.4d. Upload is pending.
