### ISSUE TITLE
Armor plus anvil crashes

### ISSUE THREAD

**Issue by DMSledge** [RayzoRayy/RaysDongles#15]
Putting the armour from this mod into the anvil with a book causes a crash.

Error: java.lang.ClassCastException: com.rbs.slurpiesdongles.armor.materials.ArmorMaterials$$Lambda$2838/1433988478 cannot be cast to net.minecraft.item.crafting.Ingredient

 Forge Version- 30.0.36
Minecraft Version- 1.15.1
Slurpie's Dongles Version(Please indicate exactly which version of my mod you are using)- 3.0.2

**Comment by RayzoRayy** [comment]
Thank you for the report. Fixed, a release is coming soon.
