### ISSUE TITLE
Missing recipes

### ISSUE THREAD

**Issue by k4mix** [RayzoRayy/RaysDongles#16]
**Describe the bug**
some of recipes are missing  i used crafttweaker to change some of them:
craftingTable.addShapeless("bricks", <item:slurpiesdongles:yellow_bricks>, [<item:minecraft:bricks>, <item:minecraft:yellow_dye> ], null);
craftingTable.addShapeless("bricks", <item:slurpiesdongles:green_bricks>, [<item:minecraft:bricks>, <item:minecraft:green_dye> ], null);
craftingTable.addShapeless("dust", <item:slurpiesdongles:green_glowstone_dust>, [<item:minecraft:glowstone_dust>, <item:minecraft:green_dye> ], null);
craftingTable.addShapeless("dust", <item:slurpiesdongles:red_glowstone_dust>, [<item:minecraft:glowstone_dust>, <item:minecraft:redstone> ], null);

**Screenshots**
logs
[latest.log](https://github.com/RayzoRayy/RaysDongles/files/4132280/latest.log)

**Please complete the following information**
 Forge Version- 31.0.1
Minecraft Version- 1.15.2
Slurpie's Dongles Version- 3.0.4

**Please list all mod(s) AND version(s) here that you are currently using along side of my mod**
only this

**Comment by RayzoRayy** [comment]
I shall take a look into this as soon as I can and release a fix. Thanks for the report!

**Comment by RayzoRayy** [comment]
Recipes are fixed, release is pending release, should be available soon. Thanks for the report again!
