### ISSUE TITLE
[1.15.2]

### ISSUE THREAD

**Issue by kwpugh** [RayzoRayy/RaysDongles#17]
Hi,

Would you consider adding forge tags for your nether vanilla ores?

forge:/ores/diamond
forge:/ores/emerald
forge:/ores/iron
forge:/ores/gold
forge:/ores/coal

Thank you for considering.

Regards.

**Comment by kwpugh** [comment]
NEvermind, just saw them, duh.

**Comment by RayzoRayy** [comment]
:)
