### ISSUE TITLE
[1.14.2] missing lang for some items

### ISSUE THREAD

**Issue by kwpugh** [RayzoRayy/RaysDongles#4]
**Describe the bug**

Great job on the mod.   The lemon, cabbage, orange and tomato crops are missing labels in the lang file.  Thought I would let you know.

**To Reproduce**
3. What happens '....'

**Expected behavior**

**Screenshots**

**Please complete the following information**
 Forge Version- 
Minecraft Version- 
Slurpie's Dongles Version(Please indicate exactly which version of my mod you are using)- 

**Please list all mod(s) AND version(s) here that you are currently using along side of my mod**

**Additional context**

**Comment by RayzoRayy** [comment]
Thanks. I'll release a fix for this once I get world gen working most likely.

**Comment by RayzoRayy** [comment]
Doesn't appear to be an issue in the lang file as they are in there. For some reason there just not showing up. If you give yourself the item with the /give command the name appears fine, they just aren't showing up under my creative tab, nor the search bar for some reason.
