### ISSUE TITLE
Possible mod conflict with grass drops - Prefab

### ISSUE THREAD

**Issue by ProsperCraft** [RayzoRayy/RaysDongles#8]
https://github.com/Brian-Wuest/MC-Prefab/issues/104
Just added prefab to the pack, it used to crash before it updated, now it just fails to place blocks.

Slurpies Dongles-1.14.4-2.0.3

**Comment by RayzoRayy** [comment]
There shouldn't be a conflict with grass drops if that is what you are referring to. I no longer use the method of json, or injecting for grass drops. Un-fortunately the method im using isin't the best for adding drops, but it shouldn't cause conflict. I'm out of ideas on what to do for grass drops until Forge implements the new PR. Although don't see how my current method of grass drops would cause any conflicts.

**Comment by RayzoRayy** [comment]
Try downgrading my version of slurpies dongles to 1.0.8 and see if the issue persists. If it doesn't, then that would be my mod at fault with the method im using for implementing grass drops. Keep me updated, thanks

**Comment by RayzoRayy** [comment]
I see the other persons reply. As a workaround what ill do is disable my crops dropping from grass seeds, and create a bush that spawns around the world similar to grass so when the player breaks that, they will obtain my crops.

**Comment by ProsperCraft** [comment]
You want me to downgrade to 1.08(is this built on forge .45?) or wait for the update?

**Comment by RayzoRayy** [comment]
Yes 1.0.8 is on Forge 45. Yeah try that in the meantime. See if it still happens. If it doesn't, its my mod. If it does, its not. Either way the updates coming out soonish, but give that a try and see what happens. Thanks

**Comment by ProsperCraft** [comment]
Totally works with 1.08

**Comment by ProsperCraft** [comment]
On a side note, your corn dropped from the grass that prefab broke.

**Comment by RayzoRayy** [comment]
Not sure what that means from your last comment? & okay, update will be out soon for Wild Crops

**Comment by ProsperCraft** [comment]
When you place a prefab house, it breaks the blocks and voids them and breaks the grass and doesn't void the flowers and seeds, I got one of your mods corn seeds.

**Comment by RayzoRayy** [comment]
Oh. Thats probably because of the method I was using to spawn seeds in the world from breaking grass

**Comment by RayzoRayy** [comment]
Update should be out in about 10 minutes. This will by default, enable a Wild Crops plant to spawn around the world. In the configs you are able to enable or disable this.(By disabling this, you will no longer be able to obtain my crops. Also if you disable in pre-loaded chunks obviously the crops that already spawned will stay. This will also require new chunks to find the plant) My crops will no longer drop from breaking grass. Also in the configs you can configure how often the Wild Crops spawns.  On another note, this should stop the stacktrace on your server as well.

**Comment by WenXin20** [comment]
I am still seeing this issue with version 2.0.4c. The Prefab Starter house won't place and instead prints an error in the log.

Please see Brian-Wuest/MC-Prefab#110 for more info.

**Comment by RayzoRayy** [comment]
Looks like i forgot to remove the OnBlockBreak event being called, this is no longer used as i now use wild crops to drop my seed and food items, i will try and get an update out asap and fix this. Currently at work. Sorry i forgot to remove this!

**Comment by WenXin20** [comment]
Thanks! No rush needed.

**Comment by RayzoRayy** [comment]
Issue should be fixed in latest release @WenXin20 2.0.4d.

**Comment by WenXin20** [comment]
Thanks!
