### ISSUE TITLE
Question - Compatibility w MineAndSlash

### ISSUE THREAD

**Issue by LimeTheOn** [RayzoRayy/RaysDongles#9]
I'm having trouble adding your weapons to MineAndSlashes Compatible item list(its just a text file where we can add things like slurpiesdongles:topaz_axe specify that its an axe and set droprates and such). I'm just interested if your swords/axes/hammers are coded uniqely and all my tries were in vain or keep trying and looking(already been 2 days) for an error on my side :D

@RobertSkalko
I feel like this is eventually gonna get to you too because Dongles adds hammers and battle-axes and great armor(those work) that fits with m&s style so people are gonna wonder what's up. If you happen to have some ideas they would be appreciated but I didn't want to open separate issues. Also here's the script for it but again I couldn't find any issues with it.

[SDWeapons.txt](https://github.com/RayzoRayy/RaysDongles/files/3511739/SDWeapons.txt)

**Comment by LimeTheOn** [comment]
Now looking at it the 50th time right after uploading I realize dongles doesn't add the stone sword and axe as they're vanilla...but it still doesn't work after fixing that.

**Comment by RobertSkalko** [comment]
What's the problem exactly? What version of my mod are you using? Did you disable compatible items in config? ..

**Comment by LimeTheOn** [comment]
I’m on mobile at the moment will take a hot 30 min to specify all that but given that everything else works im gonna say that compatible items are enabled, im using forge 28.0.49. Not gonna say latest...but...latest version of your mod at the time of the original post.

**Comment by RobertSkalko** [comment]
ok. its ur problem. ur json is invalid

https://jsonformatter.curiousconcept.com/

go there to find out where and why

1 problem i found was "slurpiesdongles:ruby_lumber_axe: {

is missing a "

**Comment by LimeTheOn** [comment]
Everyday I learn something new, never imagined something like that site existed. Thank you!

**Comment by LimeTheOn** [comment]
Confirmed noob here! Closing the issue :)
